#!/usr/bin/env bash
#
# SubagentStop hook.
# Appends a timestamped entry to a daily session log at
# .squad/log/<YYYY-MM-DD>-session.md whenever a subagent finishes.
#
# The hook payload from Claude Code does not always include the subagent's
# name (see anthropics/claude-code#7881); newer payloads include agent_id and
# agent_type. We use whatever we can get and fall back to a generic label.
#
# Exit codes:
#   0 — always (logging never blocks).

set -uo pipefail

payload="$(cat 2>/dev/null || true)"

# Parse the fields we need with one python3 call. Output is tab-separated
# so we can read it cleanly.
parsed="$(
  printf '%s' "$payload" | python3 -c '
import json,sys
try:
    d = json.loads(sys.stdin.read())
except Exception:
    d = {}
fields = [
    "true" if d.get("stop_hook_active") else "false",
    d.get("cwd",""),
    d.get("session_id",""),
    d.get("transcript_path") or d.get("agent_transcript_path","") or "",
    d.get("agent_id",""),
    d.get("agent_type",""),
]
print("\t".join(f.replace("\t"," ").replace("\n"," ") for f in fields))
' 2>/dev/null
)"

IFS=$'\t' read -r STOP_ACTIVE PAYLOAD_CWD SESSION_ID TRANSCRIPT_PATH AGENT_ID AGENT_TYPE <<<"$parsed"

# Avoid recursion when a Stop hook is already active.
[ "${STOP_ACTIVE:-false}" = "true" ] && exit 0

# Resolve project root.
project_dir="${CLAUDE_PROJECT_DIR:-${PAYLOAD_CWD:-$PWD}}"
[ -z "$project_dir" ] && project_dir="$PWD"

log_dir="$project_dir/.squad/log"
mkdir -p "$log_dir"

today="$(date -u +%Y-%m-%d)"
ts="$(date -u +%H:%M:%SZ)"
log_file="$log_dir/${today}-session.md"

# Try to recover the subagent's last assistant message for a one-line summary.
summary=""
if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "$TRANSCRIPT_PATH" ]; then
  summary="$(python3 -c '
import json,sys
path = sys.argv[1]
last_text = ""
try:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            role = obj.get("role") or obj.get("type")
            if role != "assistant":
                continue
            msg = obj.get("message") or obj
            content = msg.get("content") if isinstance(msg, dict) else None
            if isinstance(content, str):
                last_text = content
            elif isinstance(content, list):
                for blk in content:
                    if isinstance(blk, dict) and blk.get("type") == "text":
                        t = blk.get("text","")
                        if t:
                            last_text = t
except Exception:
    pass
last_text = " ".join(last_text.split())
print(last_text[:160])
' "$TRANSCRIPT_PATH" 2>/dev/null || true)"
fi

# Initialise the daily log with a header on first write.
if [ ! -s "$log_file" ]; then
  {
    printf '# Session log — %s\n\n' "$today"
    printf 'Auto-generated by `.claude/hooks/session-logger.sh` on each `SubagentStop`.\n\n'
  } >> "$log_file"
fi

{
  printf -- '- **%s** ' "$ts"
  if [ -n "${AGENT_TYPE:-}" ]; then
    printf '`%s`' "$AGENT_TYPE"
  elif [ -n "${AGENT_ID:-}" ]; then
    printf '`%s`' "$AGENT_ID"
  else
    printf '`subagent`'
  fi
  if [ -n "${SESSION_ID:-}" ]; then
    short="${SESSION_ID:0:8}"
    printf ' (session `%s`)' "$short"
  fi
  printf ' finished'
  if [ -n "${summary:-}" ]; then
    printf ' — %s' "$summary"
  fi
  printf '\n'
} >> "$log_file"

exit 0
