#!/usr/bin/env bash
#
# SubagentStop hook.
# Appends a timestamped entry to a daily session log at
# .squad/log/<YYYY-MM-DD>-session.md whenever a subagent finishes.
#
# The hook payload from Claude Code does not always include the subagent's
# name (see anthropics/claude-code#7881); newer payloads include agent_id and
# agent_type. We use whatever we can get and fall back to a generic label.
#
# Exit codes:
#   0 — always (logging never blocks).

set -uo pipefail

# 🔴-4 (PR #358 review round 1): this hook's own contract is "0 -- always
# (logging never blocks)", so a missing/broken python3 cannot be turned into
# a refusal via exit code -- the fail-closed direction available to a
# never-blocking hook is to write NOTHING rather than a garbled or
# mislabeled entry (a missing log row is honest about what happened; a row
# claiming a bogus agent/timestamp because the parser silently produced
# empty fields is not). Checked once, here, before the payload is even read.
command -v python3 >/dev/null 2>&1 || {
  echo "🚫 session-logger.sh: python3 is required to parse this SubagentStop payload and is not on PATH -- skipping this entry rather than writing one with silently empty fields." >&2
  exit 0
}

payload="$(cat 2>/dev/null || true)"

# Parse the fields we need with one python3 call. Output is tab-separated
# so we can read it cleanly.
parsed="$(
  printf '%s' "$payload" | python3 -c '
import json,sys
try:
    d = json.loads(sys.stdin.read())
except Exception:
    d = {}
fields = [
    "true" if d.get("stop_hook_active") else "false",
    d.get("cwd",""),
    d.get("session_id",""),
    d.get("transcript_path") or d.get("agent_transcript_path","") or "",
    d.get("agent_id",""),
    d.get("agent_type",""),
]
print("\t".join(f.replace("\t"," ").replace("\n"," ") for f in fields))
' 2>/dev/null
)"

IFS=$'\t' read -r STOP_ACTIVE PAYLOAD_CWD SESSION_ID TRANSCRIPT_PATH AGENT_ID AGENT_TYPE <<<"$parsed"

# Avoid recursion when a Stop hook is already active.
[ "${STOP_ACTIVE:-false}" = "true" ] && exit 0

# Resolve project root.
project_dir="${CLAUDE_PROJECT_DIR:-${PAYLOAD_CWD:-$PWD}}"
[ -z "$project_dir" ] && project_dir="$PWD"

log_dir="$project_dir/.squad/log"
mkdir -p "$log_dir"

today="$(date -u +%Y-%m-%d)"
ts="$(date -u +%H:%M:%SZ)"
log_file="$log_dir/${today}-session.md"

# Try to recover the subagent's last assistant message for a one-line summary.
summary=""
if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "$TRANSCRIPT_PATH" ]; then
  summary="$(python3 -c '
import json,sys
path = sys.argv[1]
last_text = ""
try:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            role = obj.get("role") or obj.get("type")
            if role != "assistant":
                continue
            msg = obj.get("message") or obj
            content = msg.get("content") if isinstance(msg, dict) else None
            if isinstance(content, str):
                last_text = content
            elif isinstance(content, list):
                for blk in content:
                    if isinstance(blk, dict) and blk.get("type") == "text":
                        t = blk.get("text","")
                        if t:
                            last_text = t
except Exception:
    pass
last_text = " ".join(last_text.split())
print(last_text[:160])
' "$TRANSCRIPT_PATH" 2>/dev/null || true)"
fi

# Initialise the daily log with a header on first write.
if [ ! -s "$log_file" ]; then
  {
    printf '# Session log — %s\n\n' "$today"
    printf 'Auto-generated by `.claude/hooks/session-logger.sh` on each `SubagentStop`.\n\n'
  } >> "$log_file"
fi

{
  printf -- '- **%s** ' "$ts"
  if [ -n "${AGENT_TYPE:-}" ]; then
    printf '`%s`' "$AGENT_TYPE"
  elif [ -n "${AGENT_ID:-}" ]; then
    printf '`%s`' "$AGENT_ID"
  else
    printf '`subagent`'
  fi
  if [ -n "${SESSION_ID:-}" ]; then
    short="${SESSION_ID:0:8}"
    printf ' (session `%s`)' "$short"
  fi
  printf ' finished'
  if [ -n "${summary:-}" ]; then
    printf ' — %s' "$summary"
  fi
  printf '\n'
} >> "$log_file"

# ---------------------------------------------------------------------------
# Pass cost — wall-clock per design phase, keyed by slug.
#
# dreamer-convergence's memory is the only place that answers whether the dual
# track earns what it costs, and until now the novelty hit rate had no
# denominator: half an answer. This supplies the other half.
#
# Timing comes from the transcript's own first and last timestamps rather than
# from a wrapper, because a SubagentStop hook only ever sees the end. If the
# transcript carries no timestamps the row is still written with a blank
# duration -- a row that records the phase ran is worth more than no row.
#
# Only the design-pass phase agents are recorded. Builders run in worktrees on
# their own schedule and their cost is a different question.
# ---------------------------------------------------------------------------
case "${AGENT_TYPE:-}" in
  architect|scope-warden|dreamer-first-principles|dreamer-informed|\
  dreamer-convergence|realist|critic|spec-author|reviewer-blind|reviewer-reconcile)
    cost_file="$log_dir/pass-cost.md"

    # Slug: the design pass whose directory was touched most recently.
    slug="$(python3 -c '
import os, sys
root = sys.argv[1]
design = os.path.join(root, ".squad", "design")
best, name = None, ""
if os.path.isdir(design):
    for d in os.listdir(design):
        p = os.path.join(design, d)
        if not os.path.isdir(p):
            continue
        try:
            m = max((os.path.getmtime(os.path.join(p, f)) for f in os.listdir(p)), default=None)
        except OSError:
            m = None
        if m is not None and (best is None or m > best):
            best, name = m, d
print(name)
' "$project_dir" 2>/dev/null || true)"
    [ -z "$slug" ] && slug="(no pass)"

    duration=""
    if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "$TRANSCRIPT_PATH" ]; then
      duration="$(python3 -c '
import json, sys, datetime
path = sys.argv[1]
stamps = []
try:
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            t = obj.get("timestamp") or (obj.get("message") or {}).get("timestamp") \
                if isinstance(obj.get("message"), dict) else obj.get("timestamp")
            if isinstance(t, str):
                try:
                    stamps.append(datetime.datetime.fromisoformat(t.replace("Z", "+00:00")))
                except Exception:
                    pass
except Exception:
    pass
if len(stamps) >= 2:
    secs = int((max(stamps) - min(stamps)).total_seconds())
    print("%dm %02ds" % (secs // 60, secs % 60) if secs >= 60 else "%ds" % secs)
' "$TRANSCRIPT_PATH" 2>/dev/null || true)"
    fi

    if [ ! -s "$cost_file" ]; then
      {
        printf '# Pass cost\n\n'
        printf 'Wall-clock per design phase, keyed by slug. Appended by\n'
        printf '`.claude/hooks/session-logger.sh` on every `SubagentStop` from a phase agent.\n\n'
        printf 'Read by `dreamer-convergence`, whose memory is the only place that answers\n'
        printf 'whether the dual track earns its cost. The novelty hit rate is a numerator;\n'
        printf 'this is the denominator. **If the novelty hit rate stays at zero, the\n'
        printf 'charter requires convergence to say so plainly** — a topology that cannot\n'
        printf 'report its own uselessness will never be dismantled.\n\n'
        printf 'A blank duration means the transcript carried no usable timestamps. The row\n'
        printf 'still records that the phase ran.\n\n'
        printf '| when | slug | phase | wall-clock |\n'
        printf '|---|---|---|---|\n'
      } >> "$cost_file"
    fi
    printf '| %sT%s | %s | `%s` | %s |\n' \
      "$today" "$ts" "$slug" "${AGENT_TYPE}" "${duration:-—}" >> "$cost_file"
    ;;
esac

exit 0
