// =============================================================================
// Virtual DOM Attributes
// =============================================================================
// Platform-independent attribute types for virtual DOM elements.
//
// There are two kinds:
//   - Attribute(Id, Name, Value) — a plain HTML attribute (class, href, ...)
//   - Handler(EventName, CommandId, Command, Id, WithData, DataType) — an event binding
//
// Handler extends Attribute and renders as a data-event-{name} attribute
// in the DOM. The CommandId links the DOM attribute to the registered
// event handler in the runtime's handler registry.
//
// This design enables event delegation: the browser registers a single
// listener per event type at the document level. When an event fires,
// the runtime looks up the CommandId from the target element's
// data-event-{name} attribute and dispatches the corresponding message.
// =============================================================================

using System.Collections.Frozen;

namespace Picea.Abies.DOM;

/// <summary>
/// An attribute on a virtual DOM element — either a plain HTML attribute
/// or an event handler.
/// </summary>
/// <param name="Id">Unique identifier, typically generated by Praefixum at compile time.</param>
/// <param name="Name">The attribute name (e.g., "class", "href", "data-event-click").</param>
/// <param name="Value">The attribute value.</param>
public record Attribute(string Id, string Name, string Value);

/// <summary>
/// An event handler attribute. Renders as <c>data-event-{EventName}="{CommandId}"</c> in HTML.
/// The runtime uses the <see cref="CommandId"/> to look up the handler in its registry.
/// </summary>
/// <remarks>
/// Handlers support two modes:
/// <list type="bullet">
///   <item><b>Static message</b>: <see cref="Command"/> is set, dispatched as-is (e.g., <c>onclick(new Increment())</c>).</item>
///   <item><b>Data-carrying</b>: <see cref="WithData"/> is set, called with deserialized event data
///   to produce a message (e.g., <c>oninput(e =&gt; new TextChanged(e.Value))</c>).</item>
/// </list>
/// </remarks>
/// <param name="EventName">The DOM event name (e.g., "click", "input", "change").
/// Note: This is distinct from the inherited <c>Attribute.Name</c> property,
/// which returns the full attribute name (e.g., "data-event-click").
/// C# record inheritance means <c>Attribute.Name</c> gets the transformed
/// value passed to the base constructor, so <c>Handler.Name</c> also returns
/// "data-event-click", not "click". Use <c>EventName</c> when you need the
/// raw DOM event type.</param>
/// <param name="CommandId">Unique identifier linking this handler to its runtime registration.</param>
/// <param name="Command">The static message to dispatch (null when <paramref name="WithData"/> is set).</param>
/// <param name="Id">Unique identifier for this attribute node.</param>
/// <param name="WithData">Factory function that creates a message from deserialized event data.</param>
/// <param name="Deserializer">Trim-safe deserializer for event data JSON. Provided by the
/// <c>on&lt;T&gt;</c> factory using a source-generated <see cref="System.Text.Json.Serialization.JsonSerializerContext"/>.</param>
public record Handler(
    string EventName,
    string CommandId,
    Message? Command,
    string Id,
    Func<object?, Message>? WithData = null,
    Func<string, object?>? Deserializer = null)
    : Attribute(Id, $"data-event-{EventName}", CommandId);

/// <summary>
/// Well-known event attribute name cache to avoid string interpolation at runtime.
/// </summary>
public static class EventAttributeNames
{
    private static readonly FrozenDictionary<string, string> Cache = new Dictionary<string, string>
    {
        ["click"] = "data-event-click",
        ["dblclick"] = "data-event-dblclick",
        ["input"] = "data-event-input",
        ["change"] = "data-event-change",
        ["submit"] = "data-event-submit",
        ["keydown"] = "data-event-keydown",
        ["keyup"] = "data-event-keyup",
        ["keypress"] = "data-event-keypress",
        ["focus"] = "data-event-focus",
        ["blur"] = "data-event-blur",
        ["mousedown"] = "data-event-mousedown",
        ["mouseup"] = "data-event-mouseup",
        ["mousemove"] = "data-event-mousemove",
        ["mouseenter"] = "data-event-mouseenter",
        ["mouseleave"] = "data-event-mouseleave",
        ["mouseover"] = "data-event-mouseover",
        ["mouseout"] = "data-event-mouseout",
        ["wheel"] = "data-event-wheel",
        ["scroll"] = "data-event-scroll",
        ["touchstart"] = "data-event-touchstart",
        ["touchmove"] = "data-event-touchmove",
        ["touchend"] = "data-event-touchend",
        ["pointerdown"] = "data-event-pointerdown",
        ["pointerup"] = "data-event-pointerup",
        ["pointermove"] = "data-event-pointermove",
        ["contextmenu"] = "data-event-contextmenu",
        ["drag"] = "data-event-drag",
        ["dragstart"] = "data-event-dragstart",
        ["dragend"] = "data-event-dragend",
        ["dragover"] = "data-event-dragover",
        ["drop"] = "data-event-drop",
        ["dragenter"] = "data-event-dragenter",
        ["dragleave"] = "data-event-dragleave",
        ["copy"] = "data-event-copy",
        ["cut"] = "data-event-cut",
        ["paste"] = "data-event-paste",
        ["animationstart"] = "data-event-animationstart",
        ["animationend"] = "data-event-animationend",
        ["transitionend"] = "data-event-transitionend",
        ["load"] = "data-event-load",
        ["error"] = "data-event-error",
        ["resize"] = "data-event-resize",
        ["select"] = "data-event-select",
        ["reset"] = "data-event-reset",
        ["toggle"] = "data-event-toggle",
    }.ToFrozenDictionary();

    /// <summary>
    /// Gets the data-event attribute name for the given event name.
    /// Uses the frozen dictionary cache for common events, falls back to interpolation.
    /// </summary>
    public static string Get(string eventName) =>
        Cache.TryGetValue(eventName, out var cached) ? cached : $"data-event-{eventName}";
}
